# Generated by Django 5.2.12 on 2026-04-01 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score_overall', models.IntegerField(default=0)),
                ('score_seo', models.IntegerField(default=0)),
                ('score_accessibility', models.IntegerField(default=0)),
                ('score_performance', models.IntegerField(default=0)),
                ('issues_json', models.TextField(default='[]')),
                ('suggestions_json', models.TextField(default='[]')),
                ('page_weight_kb', models.FloatField(default=0.0)),
                ('load_time_seconds', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_a', models.URLField()),
                ('url_b', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scan_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_a', to='analyzer.websitescan')),
                ('scan_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_b', to='analyzer.websitescan')),
            ],
        ),
    ]
